version: '3.8'
services:
  
  mysql:
    image: mysql:latest
    container_name: "teather_database"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - inova_network

networks:
  inova_network:
    driver: bridge